# commit to be tagged for the new release
commit = "HEAD"

project_name = "sbc-jetson"
github_repo = "siderolabs/sbc-jetson"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v0.1.2"
pre_release = false

# [notes]
